version: '3.5'
services:
  alist-rename:
    image: crpi-zutrieltt9z6q9p7.cn-shanghai.personal.cr.aliyuncs.com/awordx/open_alist_strm_rename:latest
    container_name: alist-rename
    ports:
      - "5050:5050"   # API服务端口
    volumes:
      - ./data:/usr/local/data                     #存放电影数据以及日志文件
      - ./config:/usr/local/config                 #存放配置文件
      - ./alist_strm:/alist_strm                   #右边alist_strm是容器内存放生成的strm文件
    restart: always

